apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devcrumbs-data-pvc
spec:
  accessModes:
  - ReadWriteMany  # Allow multiple pods to access
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard  # Change to your storage class
